import type { Movie } from "./movie-data"

export const upcomingMovies: Movie[] = [
  {
    id: "upcoming-1",
    title: "Dune: Part Two",
    year: 2024,
    director: "Denis Villeneuve",
    cast: ["Timothée Chalamet", "Zendaya", "Rebecca Ferguson"],
    genre: ["Action", "Adventure", "Sci-Fi"],
    plot: "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.",
    posterUrl: "/placeholder.svg?height=600&width=400",
    trailerUrl: "https://www.youtube.com/embed/8g18jFHCLXk",
    runtime: 165,
    ratings: {
      imdb: 8.7,
      rottenTomatoes: 92,
      metacritic: 82,
    },
    language: "English",
    country: "USA",
    similar: ["7", "3", "1"],
  },
  {
    id: "upcoming-2",
    title: "Gladiator II",
    year: 2024,
    director: "Ridley Scott",
    cast: ["Paul Mescal", "Denzel Washington", "Pedro Pascal"],
    genre: ["Action", "Drama", "History"],
    plot: "The story follows Lucius, the son of Lucilla, as he navigates the Roman Empire years after the events of the first film.",
    posterUrl: "/placeholder.svg?height=600&width=400",
    trailerUrl: "https://www.youtube.com/embed/8g18jFHCLXk",
    runtime: 150,
    ratings: {
      imdb: 0,
      rottenTomatoes: 0,
      metacritic: 0,
    },
    language: "English",
    country: "USA",
    similar: ["11", "12", "13"],
  },
  {
    id: "upcoming-3",
    title: "Furiosa: A Mad Max Saga",
    year: 2024,
    director: "George Miller",
    cast: ["Anya Taylor-Joy", "Chris Hemsworth", "Tom Burke"],
    genre: ["Action", "Adventure", "Sci-Fi"],
    plot: "The origin story of renegade warrior Furiosa before her encounter with Mad Max.",
    posterUrl: "/placeholder.svg?height=600&width=400",
    trailerUrl: "https://www.youtube.com/embed/8g18jFHCLXk",
    runtime: 140,
    ratings: {
      imdb: 0,
      rottenTomatoes: 0,
      metacritic: 0,
    },
    language: "English",
    country: "Australia",
    similar: ["7", "8", "9"],
  },
  {
    id: "upcoming-4",
    title: "Joker: Folie à Deux",
    year: 2024,
    director: "Todd Phillips",
    cast: ["Joaquin Phoenix", "Lady Gaga", "Zazie Beetz"],
    genre: ["Crime", "Drama", "Thriller"],
    plot: "Arthur Fleck, institutionalized at Arkham Asylum, continues to struggle with his dual identity as the musical drama unfolds.",
    posterUrl: "/placeholder.svg?height=600&width=400",
    trailerUrl: "https://www.youtube.com/embed/8g18jFHCLXk",
    runtime: 135,
    ratings: {
      imdb: 0,
      rottenTomatoes: 0,
      metacritic: 0,
    },
    language: "English",
    country: "USA",
    similar: ["5", "6", "11"],
  },
  {
    id: "upcoming-5",
    title: "Deadpool & Wolverine",
    year: 2024,
    director: "Shawn Levy",
    cast: ["Ryan Reynolds", "Hugh Jackman", "Emma Corrin"],
    genre: ["Action", "Adventure", "Comedy"],
    plot: "Deadpool teams up with Wolverine in this highly anticipated crossover event.",
    posterUrl: "/placeholder.svg?height=600&width=400",
    trailerUrl: "https://www.youtube.com/embed/8g18jFHCLXk",
    runtime: 130,
    ratings: {
      imdb: 0,
      rottenTomatoes: 0,
      metacritic: 0,
    },
    language: "English",
    country: "USA",
    similar: ["4", "7", "9"],
  },
  {
    id: "upcoming-6",
    title: "Mission: Impossible 8",
    year: 2025,
    director: "Christopher McQuarrie",
    cast: ["Tom Cruise", "Hayley Atwell", "Simon Pegg"],
    genre: ["Action", "Adventure", "Thriller"],
    plot: "Ethan Hunt returns for another impossible mission in this action-packed sequel.",
    posterUrl: "/placeholder.svg?height=600&width=400",
    trailerUrl: "https://www.youtube.com/embed/8g18jFHCLXk",
    runtime: 155,
    ratings: {
      imdb: 0,
      rottenTomatoes: 0,
      metacritic: 0,
    },
    language: "English",
    country: "USA",
    similar: ["8", "2", "4"],
  },
]

// Update the allMovies export in movie-data.ts
export const allMoviesWithUpcoming = [...upcomingMovies]
