import type { Movie } from "./movie-data"

export const upcomingMovies: Movie[] = [
  {
    id: "upcoming-1",
    title: "Dune: Part Two",
    year: 2024,
    director: "Denis Villeneuve",
    genre: ["Action", "Adventure", "Sci-Fi"],
    plot: "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.",
    posterUrl: "/placeholder.svg?height=600&width=400",
    runtime: 165,
    ratings: {
      imdb: 8.7,
      rottenTomatoes: '92',
      metacritic: 82,
    },
    language: ['English'],
    country: ['USA'],
    released: '',
    writer: '',
    actors: [],
    awards: '',
    metascore: 0,
    imdbVotes: 0,
    type: 'movie',
    dvd: '',
    boxOffice: '',
    production: '',
    website: '',
    imdb_id: '',
    imdbId: '',
  },
  {
    id: "upcoming-2",
    title: "Gladiator II",
    year: 2024,
    director: "Ridley Scott",
    genre: ["Action", "Drama", "History"],
    plot: "The story follows Lucius, the son of Lucilla, as he navigates the Roman Empire years after the events of the first film.",
    posterUrl: "/placeholder.svg?height=600&width=400",
    runtime: 150,
    ratings: {
      imdb: 0,
      rottenTomatoes: '0',
      metacritic: 0,
    },
    language: ['English'],
    country: ['USA'],
    released: '',
    writer: '',
    actors: [],
    awards: '',
    metascore: 0,
    imdbVotes: 0,
    type: 'movie',
    dvd: '',
    boxOffice: '',
    production: '',
    website: '',
    imdb_id: '',
    imdbId: '',
  },
  {
    id: "upcoming-3",
    title: "Furiosa: A Mad Max Saga",
    year: 2024,
    director: "George Miller",
    genre: ["Action", "Adventure", "Sci-Fi"],
    plot: "The origin story of renegade warrior Furiosa before her encounter with Mad Max.",
    posterUrl: "/placeholder.svg?height=600&width=400",
    runtime: 140,
    ratings: {
      imdb: 0,
      rottenTomatoes: '0',
      metacritic: 0,
    },
    language: ['English'],
    country: ['Australia'],
    released: '',
    writer: '',
    actors: [],
    awards: '',
    metascore: 0,
    imdbVotes: 0,
    type: 'movie',
    dvd: '',
    boxOffice: '',
    production: '',
    website: '',
    imdb_id: '',
    imdbId: '',
  },
  {
    id: "upcoming-4",
    title: "Joker: Folie à Deux",
    year: 2024,
    director: "Todd Phillips",
    genre: ["Crime", "Drama", "Thriller"],
    plot: "Arthur Fleck, institutionalized at Arkham Asylum, continues to struggle with his dual identity as the musical drama unfolds.",
    posterUrl: "/placeholder.svg?height=600&width=400",
    runtime: 135,
    ratings: {
      imdb: 0,
      rottenTomatoes: '0',
      metacritic: 0,
    },
    language: ['English'],
    country: ['USA'],
    released: '',
    writer: '',
    actors: [],
    awards: '',
    metascore: 0,
    imdbVotes: 0,
    type: 'movie',
    dvd: '',
    boxOffice: '',
    production: '',
    website: '',
    imdb_id: '',
    imdbId: '',
  },
  {
    id: "upcoming-5",
    title: "Deadpool & Wolverine",
    year: 2024,
    director: "Shawn Levy",
    genre: ["Action", "Adventure", "Comedy"],
    plot: "Deadpool teams up with Wolverine in this highly anticipated crossover event.",
    posterUrl: "/placeholder.svg?height=600&width=400",
    runtime: 130,
    ratings: {
      imdb: 0,
      rottenTomatoes: '0',
      metacritic: 0,
    },
    language: ['English'],
    country: ['USA'],
    released: '',
    writer: '',
    actors: [],
    awards: '',
    metascore: 0,
    imdbVotes: 0,
    type: 'movie',
    dvd: '',
    boxOffice: '',
    production: '',
    website: '',
    imdb_id: '',
    imdbId: '',
  },
  {
    id: "upcoming-6",
    title: "Mission: Impossible 8",
    year: 2025,
    director: "Christopher McQuarrie",
    genre: ["Action", "Adventure", "Thriller"],
    plot: "Ethan Hunt returns for another impossible mission in this action-packed sequel.",
    posterUrl: "/placeholder.svg?height=600&width=400",
    runtime: 155,
    ratings: {
      imdb: 0,
      rottenTomatoes: '0',
      metacritic: 0,
    },
    language: ['English'],
    country: ['USA'],
    released: '',
    writer: '',
    actors: [],
    awards: '',
    metascore: 0,
    imdbVotes: 0,
    type: 'movie',
    dvd: '',
    boxOffice: '',
    production: '',
    website: '',
    imdb_id: '',
    imdbId: '',
  },
]

// Update the allMovies export in movie-data.ts
export const allMoviesWithUpcoming = [...upcomingMovies]
